version: "3"

services:
  kafka:
    image: "bitnami/kafka:2.1.0"
    restart: unless-stopped
    ports:
      - '9092:9092'
    expose:
      - '9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  zookeeper:
    image: "bitnami/zookeeper:latest"
    restart: unless-stopped
    ports:
      - '2181:2181'
    expose:
      - '2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
