version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    expose:
      - 3306
    volumes:
      - "./mysql:/var/lib/mysql"
      - "./sql:/home"
  redis:
    image: redis:4.0
    expose:
      - 6379
  server:
    build: .
    ports:
      - "18050:18104"
    depends_on:
      - mysql
      - redis
    volumes:
      - "./workhours:/home/workhours"