version: '3'

services:
  gitlab:
    image: 'gitlab/gitlab-ee:14.5.2-ee.0'
    restart: unless-stopped
    environment:
      TZ: 'Asia/Shanghai'
      GENERATED_EXTERNAL_URL: |
        external_url 'http://192.168.92.171:8880'
    ports:
      - '8880:8880'
      - '443:443'
      - '2212:22'
    volumes:
      - './etc:/etc/gitlab'
      - './log:/var/log/gitlab'
      - './opt:/var/opt/gitlab'